### ISSUE TITLE
How to use it???

### ISSUE THREAD

**Issue by kodekrendel** [posva/vue-mdc#183]
Hi.

It literaly no docs and no example. What's the markup? How to use it?

**Comment by posva** [comment]
hey. I'll probably add more docs in the following weeks, I'm quite in the middle of something for the rest of the week. You can find how to add vue-mdc to your project in the readme and then you can find usage in the test files. Most components are really easy to check (for props and methods), so you can check that as well.
Keep in mind the lib is far from being ready 🙂
