### ISSUE TITLE
How to use single component?

### ISSUE THREAD

**Issue by jerakode** [posva/vue-mdc#209]
Hi. 
The whole sense of MDC is ability to use not whole library, but curtain components. Is this available in vue-mdc? I didn't fin answer in Docs (since there's none)

**Comment by posva** [comment]
You can import them from the src (you need to setup scss loader with node_modules) or you can import components `import { Button } from 'vue-mdc'`
Both things will be explained in the docs 🙂

**Comment by jerakode** [comment]
> you can import components import { Button } from 'vue-mdc'

And what's next? How to register it? A component? What markup should be? Where's docs?

**Comment by posva** [comment]
It's a component, register it locally or globally. For usage you can check
the test, I have an extensive test suite so you'll be able to see how
components can be used. I'm still working on the docs at www.vue-mdc.js.org
Don't forget to include the relevant css 😁
