### ISSUE TITLE
Not working with Nuxt - SSR ready?

### ISSUE THREAD

**Issue by jerakode** [posva/vue-mdc#210]
Ok, you call it SSR ready, but it doesn't work with Nuxt.

1. Create a plugin
```
import Vue from 'vue'
import VueMdc from 'vue-mdc'
// You need a specific loader for CSS files like https://github.com/webpack/css-loader
import 'vue-mdc/dist/vue-mdc.css'

Vue.use(VueMdc)
```
2. Extend `nuxt.config`
```
  plugins: [
    {src: '~plugins/mdc', ssr: false}
  ],
```
3. Markup (pug)
```
button.mdc-button click
```
4. Only CSS are applied - so it's not working.

**Comment by posva** [comment]
It does work, you may want to have a look at the wip docs https://github.com/posva/vue-mdc.js.org

**Comment by jerakode** [comment]
omg, this is challenging.

**Comment by posva** [comment]
what do you mean 😆 ?

**Comment by jerakode** [comment]
@posva well, I've tried another markup from that example repo 

```
MdcButton(v-ripple) click
```
It doesn't work anyway. My plugin stays above and it looks like yours, beside `const props = {}` 
I just want to try simple example and I can't do that. 
Unbelievable.
