### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Tim15** [posva/vue-mdc#244]
Do you have a strategy for adding documentation? Are you planing on using a specific system like JSDoc, or just some basic markdown, or the Github Wiki? I would be happy to help with anything.

The code is fairly clear to read and see the options, but I think some basic documentation would really help people get started with this project.

**Comment by posva** [comment]
The ongoing work is at https://github.com/posva/vue-mdc.js.org
I have been undergoing under too many things for a couple of months and haven't been able to set out the foundation yet... I'll do my best to get the foundation ready asap so people like you can help

integrating mdc with vue is actually quite easy, but I really struggle to find the moment to finish the foundation of docs so people can easily contribute :(
