### ISSUE TITLE
Handle dialog accept/cancel events

### ISSUE THREAD

**Issue by hanxue** [posva/vue-mdc#257]
I have looked at the https://github.com/posva/vue-mdc/blob/master/src/Dialog/Dialog.vue source and don't see any accept/cancel events. How do I handle an `accept` or `cancel` button click event?

**Comment by posva** [comment]
I think you're looking for `accepted` and `canceled` but I may rename them in the future to `accept` and `cancel` (https://github.com/posva/vue-mdc/blob/master/src/Dialog/Dialog.vue#L81-L82)
